<?php


namespace App\Models;


/**
 * App\Models\Hotels
 * @package App\Models
 * @property int $id
 * @property int $panelId
 * @property string $title
 * @property string $description
 * @property int $sort
 * @property bool $active
 * @property int $addedAt
 * @property string $panelName
 * @property string $panelSlug
 *
 */
class Ticket extends \Eloquent
{
    protected $table="tickets";
    protected $fillable = ['id','panelId','title','description','sort','active','addedAt'];
    public $timestamps = false;

    public function escapeWhenCastingToString($escape = true)
    {
        return parent::escapeWhenCastingToString(true); // TODO: Change the autogenerated stub
    }


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return int
     */
    public function getPanelId()
    {
        return $this->panelId;
    }

    /**
     * @param int $panelId
     */
    public function setPanelId($panelId)
    {
        $this->panelId = $panelId;
    }

    /**
     * @return string|null
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string|null $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @return string|null
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string|null $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return int
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * @param int $sort
     */
    public function setSort($sort)
    {
        $this->sort = $sort;
    }

    /**
     * @return bool
     */
    public function isActive()
    {
        return $this->active;
    }

    /**
     * @param bool $active
     */
    public function setActive($active)
    {
        $this->active = $active;
    }

    /**
     * @return int
     */
    public function getAddedAt()
    {
        return $this->addedAt;
    }

    /**
     * @param int $addedAt
     */
    public function setAddedAt($addedAt)
    {
        $this->addedAt = $addedAt;
    }

    /**
     * @return string
     */
    public function getPanelName()
    {
        return $this->panelName;
    }

    /**
     * @param string $panelName
     */
    public function setPanelName($panelName)
    {
        $this->panelName = $panelName;
    }

    /**
     * @return string
     */
    public function getPanelSlug()
    {
        return $this->panelSlug;
    }

    /**
     * @param string $panelSlug
     */
    public function setPanelSlug($panelSlug)
    {
        $this->panelSlug = $panelSlug;
    }
    public function __toString() {
        return json_encode($this->toArray());
    }

    public function toArray() {
        return $this->processArray(get_object_vars($this));
    }

    private function processArray($array) {

        foreach($array as $key => $value) {

            if (is_object($value)) {

                $array[$key] = $value->toArray();
            }
            if (is_array($value)) {
                $array[$key] = $this->processArray($value);
            }
        }
        return $array;
    }
}